# Project information
site_name: Interview notes
site_url: https://fadeawaylove.github.io/interview_mkdocs
site_author: 呆瓜
site_description: >-
  一个学习知识的记录

# Repository
repo_name: interview_mkdocs
repo_url: https://github.com/fadeawaylove/interview_mkdocs

theme:
  name: material
  custom_dir: material
  language: zh
  palette:
    primary: black
    scheme: default
    accent: red
  features:
    - search.highlight
    - header.autohide
    - instant
    - navigation.expand
    - tabs
    - toc.autohide
  logo: assets/logo.png
  include_search_page: false
  search_index_only: true

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - mathjaxhelper.js

extra_css:
  - customer.css

plugins:
  - search


# Page tree
nav:
  - 主页: index.md
  - 简介: intro.md
  - 算法:
      - algorithm/动态规划.md
      - algorithm/回溯法.md
  #      - Page 1.3
  - Redis:
      - redis/index.md
#      - Page 2.2
#      - Page 2.3