# Project information
site_name: Interview notes
site_url: https://fadeawaylove.github.io/interview_mkdocs
site_author: 呆瓜
site_description: >-
  一个学习知识的记录

# Repository
repo_name: interview_mkdocs
repo_url: https://github.com/fadeawaylove/interview_mkdocs

theme:
  name: material
  #  custom_dir: material
  language: zh
  palette:
    primary: black
    scheme: default
    accent: red
  features:
    - search.highlight
    - header.autohide
    - instant
    - navigation.expand
    - navigation.instant
    - tabs
    - toc.autohide
  logo: assets/logo.png
  include_search_page: false
  search_index_only: true

markdown_extensions:
  - toc:
      # toc_depth: 5
      permalink: true
  - extra
  - tables
  - fenced_code
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - mathjaxhelper.js

# 额外添加的css
# extra_css:
#   - customer.css

plugins:
  - search


# Page tree
nav:
  - 主页:
      - 简介: index.md
  - 书籍:
      - Redis: books/redis.md
  - 算法:
      - algorithm/动态规划.md
      - algorithm/回溯法.md
  - Redis:
      - redis/安装使用.md
      - redis/源码调试.md
      - 基础数据结构:
          - redis/数据结构/字符串.md

  - 文章:
      - 我是你爸爸:
          - 1: posts/index.md
          - 2: posts/index.md
  - Python:
      - python基础: python/基础.md
      - python技巧: python/技巧.md
