name: ci
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install mkdocs-material==5.5.14
      - run: pip install mkdocs-material-extensions==1.0.1
      - run: pip install mkdocs==1.1.2
      - run: pip install mkdocs-bootstrap4==0.1.4
      - run: pip install mkdocs-git-committers-plugin==0.1.10
      - run: git pull origin master
      - run: mkdocs gh-deploy --force
